// Generated by gencpp from file rover_movement/motor_command_server.msg
// DO NOT EDIT!


#ifndef ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVER_H
#define ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVER_H

#include <ros/service_traits.h>


#include <rover_movement/motor_command_serverRequest.h>
#include <rover_movement/motor_command_serverResponse.h>


namespace rover_movement
{

struct motor_command_server
{

typedef motor_command_serverRequest Request;
typedef motor_command_serverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_command_server
} // namespace rover_movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rover_movement::motor_command_server > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::rover_movement::motor_command_server&) { return value(); }
};

template<>
struct DataType< ::rover_movement::motor_command_server > {
  static const char* value()
  {
    return "rover_movement/motor_command_server";
  }

  static const char* value(const ::rover_movement::motor_command_server&) { return value(); }
};


// service_traits::MD5Sum< ::rover_movement::motor_command_serverRequest> should match 
// service_traits::MD5Sum< ::rover_movement::motor_command_server > 
template<>
struct MD5Sum< ::rover_movement::motor_command_serverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rover_movement::motor_command_server >::value();
  }
  static const char* value(const ::rover_movement::motor_command_serverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_movement::motor_command_serverRequest> should match 
// service_traits::DataType< ::rover_movement::motor_command_server > 
template<>
struct DataType< ::rover_movement::motor_command_serverRequest>
{
  static const char* value()
  {
    return DataType< ::rover_movement::motor_command_server >::value();
  }
  static const char* value(const ::rover_movement::motor_command_serverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rover_movement::motor_command_serverResponse> should match 
// service_traits::MD5Sum< ::rover_movement::motor_command_server > 
template<>
struct MD5Sum< ::rover_movement::motor_command_serverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rover_movement::motor_command_server >::value();
  }
  static const char* value(const ::rover_movement::motor_command_serverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_movement::motor_command_serverResponse> should match 
// service_traits::DataType< ::rover_movement::motor_command_server > 
template<>
struct DataType< ::rover_movement::motor_command_serverResponse>
{
  static const char* value()
  {
    return DataType< ::rover_movement::motor_command_server >::value();
  }
  static const char* value(const ::rover_movement::motor_command_serverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVER_H
