// Generated by gencpp from file rover_movement/motor_command_serverRequest.msg
// DO NOT EDIT!


#ifndef ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVERREQUEST_H
#define ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_movement
{
template <class ContainerAllocator>
struct motor_command_serverRequest_
{
  typedef motor_command_serverRequest_<ContainerAllocator> Type;

  motor_command_serverRequest_()
    : command()  {
    }
  motor_command_serverRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_command_serverRequest_

typedef ::rover_movement::motor_command_serverRequest_<std::allocator<void> > motor_command_serverRequest;

typedef boost::shared_ptr< ::rover_movement::motor_command_serverRequest > motor_command_serverRequestPtr;
typedef boost::shared_ptr< ::rover_movement::motor_command_serverRequest const> motor_command_serverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_movement::motor_command_serverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_movement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::rover_movement::motor_command_serverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_movement/motor_command_serverRequest";
  }

  static const char* value(const ::rover_movement::motor_command_serverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::rover_movement::motor_command_serverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_command_serverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_movement::motor_command_serverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_movement::motor_command_serverRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MOVEMENT_MESSAGE_MOTOR_COMMAND_SERVERREQUEST_H
